# -*- coding: utf-8 -*-
"""calculadora.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195FatWOmE9rI6RQGAVrns9mau_2M3Zjz
"""



def adicao(x, y):
  """Soma dois números."""
  return x + y

def subtracao(x, y):
  """Subtrai o segundo número do primeiro."""
  return x - y

def multiplicacao(x, y):
  """Multiplica dois números."""
  return x * y

def divisao(x, y):
  """Divide o primeiro número pelo segundo, tratando divisão por zero."""
  if y == 0:
    return "Erro: Divisão por zero!"
  else:
    return x / y

def calculadora():
  """Executa uma calculadora aritmética simples."""
  print("Selecione a operação:")
  print("1. Adição")
  print("2. Subtração")
  print("3. Multiplicação")
  print("4. Divisão")

  while True:
    escolha = input("Digite a opção (1/2/3/4): ")

    if escolha in ('1', '2', '3', '4'):
      try:
        num1 = float(input("Digite o primeiro número: "))
        num2 = float(input("Digite o segundo número: "))
      except ValueError:
        print("Entrada inválida. Por favor, digite números.")
        continue

      if escolha == '1':
        print(f"{num1} + {num2} = {adicao(num1, num2)}")

      elif escolha == '2':
        print(f"{num1} - {num2} = {subtracao(num1, num2)}")

      elif escolha == '3':
        print(f"{num1} * {num2} = {multiplicacao(num1, num2)}")

      elif escolha == '4':
        print(f"{num1} / {num2} = {divisao(num1, num2)}")

      proxima_operacao = input("Deseja fazer outra operação? (sim/não): ")
      if proxima_operacao.lower() != 'sim':
        break
    else:
      print("Opção inválida. Por favor, digite uma opção válida.")

# Para usar a calculadora, execute esta célula:
calculadora()