# -*- coding: utf-8 -*-
"""Cópia de Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJ5VS6nszRpojrphFIJVkDvAg3oygUCN
"""

i = 456
for i in range(i, (i + 12)):
  if i % 2 == 0:
    pass
  else:
      print(i)

v = [0,1]
while len(v) <= 50:
  v.append(v[-1]*2)
print(v)